### ISSUE TITLE
EPT Reader - HTTP(s) Threading Performance (Issue?)

### ISSUE THREAD

**Issue by danieldjewell** [PDAL/PDAL#3331] opened 2021-01-09 21:01 UTC
The speed of accessing EPT datasets located remotely (e.g. over HTTPS) seems extraordinarily slow.  

I suspect the causes of this might be because:
* EPT datasets are broken up into a *LOT* of individual files (one of the USGS's LIDAR scans on Amazon S3 is 420,000+ files. (https://usgs-lidar-public.s3.amazonaws.com/PA_WesternPA_1_2019/ept.json)
* Requesting even a small subset of data by setting bounds still results in a **LOT** of HTTP requests. 
* The overhead on each individual HTTP request is pretty high. 
* It *appears* that the EPT Reader defaults to 4 threads in stream mode *regardless* of the setting of threads? (see below, I might have overlooked something in arbiter ... @connormanning ?)

https://github.com/PDAL/PDAL/blob/d59be9b9bbd2d2341d55d9f16bca7433b0eeb16a/io/EptReader.cpp#L496-L516

The most ideal option would be to have an additional option for readers.ept like "net_threads" or something that could control how many network threads are used... Given the design of EPT, having the ability to run many download threads is a must. (@connormanning I'm not sure whether arbiter does any kind of HTTP pipelining/connection reuse ... same with HTTP/2 -- but AWS s3 seems to only support HTTP/2 when data is published through cloudfront)

(Not implying that EPT is poorly designed at all -- it's amazing for enabling real-time remote viewing ... e.g. in web browsers, etc. -- the only downside is when trying to subset the data, there are a HUGE number of HTTP requests required to get the data...)

**Comment by connormanning** [comment] 2021-01-09 21:14
Interesting.  This looks like a regression introduced in PDAL 2.2 to me,
can you try this with PDAL 2.1?  I believe the `threads` setting should be
respected in 2.1 in both streaming and standard mode.

**Comment by abellgithub** [comment] 2021-01-09 21:33
The thread limit of 4 is only used in streaming mode. In standard mode, the option setting should be respected.  You can force a pipeline to run in standard mode if that's what you want. The purpose of streaming mode is defeated if you download all the data into memory faster than it can be processed. Whether this is the right choice depends a lot on the size of the EPT tiles, which is also variable.

4 threads are used in Potree, for example, to fetch data, and it seems reasonably responsive with EPT.

I think that rather than guessing about the reason for slow performance some real analysis would be in order.

**Comment by connormanning** [comment] 2021-01-09 23:13
The intended purpose of this option is precisely to control the number of
concurrent RTTs though - that was my intention for this option when writing
the streaming functionality for this reader in 2.1.  The documentation for
this option: "Number of worker threads used to download and process EPT
data", to me implies clearly that your memory usage might increase if you
increase this value in stream mode.  For an opt-in setting, where the user
has seen this documentation and explicitly increased this value to add more
worker threads, it doesn't seem right to say "I'm concerned about your
memory usage so I'll silently ignore this setting".  Maybe one of those
eye-catching *Note* lines mentioning this on the option documentation would
help?

I also don't think this defeats the purpose of streaming: yes the memory
usage may be higher but the critical difference is that the memory usage is
not dependent on the size of the underlying data - you can churn through a
TB-sized set with similar performance to a MB-sized set.  To me, that is
the purpose of streaming: not necessarily complete minimization of memory
usage but rather the decoupling of memory usage from dataset size.

And I don't think a Potree comparison works here - in a renderer, the
responsiveness is a visually weighted thing where loading the most
important nodes very quickly means that it looks "responsive", while in the
context of PDAL it's about time-to-completion and overall throughput.

In my experience I would expect a noticeable performance impact here.  From
a quick test using PDAL via Conda and comparing 2.2 to 2.1 from my laptop,
reading the dataset
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NY_NewYorkCity/ept.json
to the specified resolution with readers.ept.threads=12 (only 4 of which
would actually be utilized in 2.2), I see timings:

Resolution 25:
2.1: 39s
2.2: 58s

Resolution 15:
2.1: 150s
2.2: 227s

Whether that difference can be attributed to this change or not, I can't
say with 100% certainty from this quick test, but I'd be surprised if it
wasn't a major factor.  Looking at my performance monitor I saw pretty much
identical memory usage between the two versions.  In my opinion, this
option should go back to respecting the user's setting.

**Comment by abellgithub** [comment] 2021-01-12 15:01
I spent a little time looking at the code and I don't think user thread control is the answer.

Instead, the system can make a reasonable effort at figuring out what needs to be queued, I think. The thread pool for net requests can be large and the driver can figure out how many requests to queue based on consumption of data and completion of requests.

**Comment by connormanning** [comment] 2021-01-12 16:43
I'm still not sure I understand the intent here.  What are we gaining by
disallowing the user from setting this option which was supported in the
previous release?  This is a very common control for applications which may
be downloading lots of files, see for example this doc in AWS CLI here
which describes scenarios a user might want to raise or lower this limit:
https://docs.aws.amazon.com/cli/latest/topic/s3-config.html#max-concurrent-requests.
Or for a different type of thread-intensive application, something like
Ninja build system which defaults to implicit parallelism via some
heuristic, but importantly can still be set explicitly with "-j" (which I
often use to keep it from taking all my resources while I'm doing other
things).

Even if some hidden heuristic for this worked perfectly and saturated
available bandwidth, there are instances when users may not want PDAL to
make this determination.  A magical heuristic may be fine for a default
(although I'd still tend to prefer explicit to implicit), but why disallow
an option for when the user knows precisely what they want, and tells PDAL
explicitly?

This is also inconsistent with the "threads" option in the i3s reader (
https://pdal.io/stages/readers.i3s.html), which as far as I know still
works as documented.

**Comment by abellgithub** [comment] 2021-05-10 16:49
Fixed by #3446

**Closed by abellgithub** 2021-05-10 16:49 UTC
Labels: bug
