### ISSUE TITLE
Pdal : bug with "ground" function - Gdal not recognized (can't find "classify")

### ISSUE THREAD

**Issue by Mathvarin** [PDAL/PDAL#1578] opened 2017-04-27 00:52 UTC
Hello,
I followed the first exercices with the docker toolbox (https://www.pdal.io/workshop/exercises/analysis/ground/ground.html) and everything worked fine. When I arrived at the "ground" function, I got this message : 

![bug_pdal](https://cloud.githubusercontent.com/assets/28075022/25463123/f4fc4c1a-2ac1-11e7-864a-07cd6b3a7430.png)

"PDAL: filter.pmf: Unexpected argument 'classify'.
(pdal ground Dbug) GDAL debug: GDAL: In GDALDestroy - unloading GDAL shared library"

Is anyone has an idea of the problem?

Thank you very much

Mathieu

**Comment by abellgithub** [comment] 2017-04-27 12:41
Duplicate of https://github.com/PDAL/PDAL/issues/1565.

**Comment by chambbj** [comment] 2017-04-27 14:13
Actually, @abellgithub this is a legit bug in the kernel, which is still trying to set the classify and extract options on the filter. I'll fix it up.

**Comment by chambbj** [comment] 2017-04-27 14:28
In the meantime @Mathvarin, you can always perform your processing as shown [here](https://www.pdal.io/workshop/exercises/analysis/ground/ground.html#filtering) in the second example, with or without the `outlier` and `range` filters. Additional `pmf` documentation can be found [here](https://www.pdal.io/stages/filters.pmf.html).

**Comment by Mathvarin** [comment] 2017-04-27 15:50
Thank you @chambbj  I will try that.

**Comment by Mathvarin** [comment] 2017-04-28 22:01
The second example worked fine.

**Closed** 2017-06-20 18:23 UTC
