### ISSUE TITLE
Limited gdaldriver options available to writers.gdal

### ISSUE THREAD

**Issue by gneissone** [PDAL/PDAL#1600] opened 2017-06-09 17:29 UTC
Apologies if this isn't a bug or its origin is outside PDAL.
writers.gdal seems to only be able to write to a few raster formats, namely GTiff, ENVI, and HFA. 

Shouldn't we be able to write to any of the formats listed [here](http://www.gdal.org/formats_list.html), or at least whatever subset is available to the version of gdal being used?

If I try to use a different driver, I get this error: PDAL: writers.gdal: Requested driver 'AAIGrid' does not support file creation. 

Running the latest pdal release via docker.

**Comment by abellgithub** [comment] 2017-06-09 18:58
This is a duplicate of https://github.com/PDAL/PDAL/issues/1497.

When this bubbles to the top of the list, I'll work on it.  If you're interested in tackling, let me know and I can help provide some direction.

**Closed by abellgithub** 2017-06-09 18:58 UTC

**Comment by abellgithub** [comment] 2017-06-09 19:02
Also note that GDAL provides no way to for a client to know which drivers support which raster types, complicating things for us.  I'll put a note in the documentation explaining the issue until this gets fixed.
