### ISSUE TITLE
Reprojection filter does not work in PDAL's Docker container

### ISSUE THREAD

**Issue by granitehills14** [PDAL/PDAL#1793] opened 2018-01-26 21:39 UTC
Attempting to run the reprojection filter in the docker container,  the following error is thrown:

> bash-4.3# pdal pipeline -i /data/reproject.json --readers.las.filename=/data/U_USACE_PC_20180114.laz --writers.las.filename=/data/U_USACE_PC_20180114_reprojected.laz
(pdal pipeline filters.reprojection Error) GDAL failure (6) Unable to load PROJ.4 library (libproj.so), creation of OGRCoordinateTransformation failed.
PDAL: filters.reprojection: Could not construct coordinate transformation object in createTransform

In my case I was trying to reproject from EPSG: 26918 to EPSG: 6542 but the error persists for other transformations as well. 

I conferred with a colleague who was able to reproduce the issue in his Docker build but found that it succeeded on his local build. 

Please let me know if I can provide any additional information. Thanks!

**Comment by abellgithub** [comment] 2018-01-27 15:36
Thanks for the report. We're aware of the problem. @chambbj, did we resolve the proj library inclusion/removal that was discussed?  I don't see a change in the current dockerfile.

**Comment by chambbj** [comment] 2018-01-29 15:46
Looks like it was fixed in one place, but not for all variants. I can update today. @granitehills14 can you tell me which Docker image/build you were using?

**Comment by granitehills14** [comment] 2018-01-29 16:22
@chambbj I am running the docker edge channel v. 18.01.0-ce-win48

**Comment by winsento** [comment] 2018-03-25 06:03
Add symlink to `/usr/lib/libproj.so` solve this problem:
```bash
ln -s /usr/lib/libproj.so.12 /usr/lib/libproj.so
```

**Comment by winsento** [comment] 2018-03-25 06:26
Add symlink to `/usr/lib/libproj.so` solve this problem:

``` bash
ln -s /usr/lib/libproj.so.12 /usr/lib/libproj.so
```

**Comment by hobu** [comment] 2018-03-25 15:30
We shouldn't be modifying Alpine directly. The issue is the Alpine GDAL bindings need `libproj.so` in the path for dynamic loading, and there is a package dependency that isn't correct.

**Closed** 2018-08-21 15:29 UTC

**Comment by tyrcog** [comment] 2019-05-24 21:09
In case you missed the solution (like I did), install `proj-dev` to get the symlink.
