### ISSUE TITLE
"Parser error = !" on correct Boolean logic

### ISSUE THREAD

**Issue by ATL-Flaneur** [PDAL/PDAL#3443] opened 2021-04-30 14:46 UTC
I'm running PDAL 2.2.0 on Ubuntu 20.04. The pipeline `nc_class.json` produces the following output when run with `pdal pipeline nc_class.json`:

```
Parser error = !
Parser error = !
``` 

I'm using [this data](http://fatra.cnr.ncsu.edu/foss4g2017/nc_tile_0793_016_spm.zip).

nc_class.json listing:
```
{
  "pipeline": [
    "/home/ayank/Documents/geodata/lpc/nc/nc_tile_0793_016_spm.las",
    {
      "type": "filters.assign",
      "assignment": "Classification[:]=0"
    },
    {
      "type": "filters.elm"
    },
    {
      "type": "filters.smrf",
      "where": "Classification != 7"
    },
    {
      "type": "filters.hag_delaunay"
    },
    {
      "type": "filters.outlier",
      "multiplier": 16,
      "class": 18,
      "where": "!(Classification == 2 || Classification == 7)"
    },
    {
      "type": "filters.approximatecoplanar",
      "where": "HeightAboveGround >= 2 && !(Classification == 2 || Classification == 7 || Classification == 18)"
    },
    {
      "type": "filters.outlier",
      "class": 18,
      "where": "!(Classification == 2 || Classification == 7 || Classification == 18) && Coplanar == 1"
    },
    {
      "type": "filters.assign",
      "value": "Classification = 6 WHERE (Coplanar == 1 && !(Classification == 7 || Classification == 18))"
    },
    {
      "type": "filters.covariancefeatures",
      "mode": "normalized",
      "feature_set": "Dimensionality",
      "knn": 45
    },
    {
      "type": "filters.assign",
      "value": "Classification = 4 WHERE (!(Classification == 2 || Classification == 6) && HeightAboveGround >= 3.0 && Planarity < 0.8 && Scattering > 0.1 && Verticality > 0.1)"
    },

    {
      "type": "writers.las",
      "filename": "/home/ayank/Documents/geodata/lpc/nc/nc_class.laz"
    }
  ]
}
```

The pipeline still runs and produces the expected output.

**Comment by abellgithub** [comment] 2021-04-30 15:34
Sorry I didn't remember this. Duplicate of #3256

**Closed by abellgithub** 2021-04-30 15:34 UTC
