### ISSUE TITLE
gcc 9.4.0 UUID warning

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#3522] opened 2021-08-30 21:33 UTC
Super noisy on gcc 9.4.0:

```
/opt/pdal/pdal/util/Uuid.hpp: In member function 'void pdal::Uuid::clear()':
/opt/pdal/pdal/util/Uuid.hpp:110:44: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct pdal::uuid'; use assignment or value-initialization instead [-Wclass-memaccess]
  110 |         { memset(&m_data, 0, sizeof(m_data)); }
      |                                            ^
/opt/pdal/pdal/util/Uuid.hpp:71:8: note: 'struct pdal::uuid' declared here
   71 | struct uuid
      |        ^~~~
```

**Comment by abellgithub** [comment] 2021-08-30 21:36
Duplicate of #3499

**Closed by abellgithub** 2021-08-30 21:36 UTC
Labels: bug
