### ISSUE TITLE
GDAL warnings when invoking pdal commands

### ISSUE THREAD

**Issue by jfbourgon** [PDAL/PDAL#1776] opened 2018-01-04 16:05 UTC
I'm getting some warnings when I'm invoking `pdal translate` in order to perform vertical grid shift on LAS data using a command similar to:
```
pdal translate input.laz output.laz reprojection --filters.reprojection.in_srs="EPSG:2951+5713" --filters.reprojection.out_srs="EPSG:2959+6647" --writers.las.scale_x=0.01 --writers.las.scale_y=0.01 --writers.las.scale_z=0.001

Warning 1: Cannot find pcs.csv
Warning 1: Cannot find gcs.csv
Warning 1: Cannot find datum.csv or gdal_datum.csv
```
The command completes successfully and the data seems to be properly shift however I would like to understand what may be the cause of those warnings in order to get rid of them since it may presume that something went wrong and could be misleading for users of the software.

I confirmed that I had both `GDAL_DATA` and `PROJ_LIB` environment variables are properly set and point to a location where the missing files exist.

When invoking the same command with some additional debug flags ON, it is also confirming that files lookup actually work but warnings remain:
```
export CPL_DEBUG=ON
export PROJ_DEBUG=ON

pdal translate input.laz output.laz reprojection --filters.reprojection.in_srs="EPSG:2951+5713" --filters.reprojection.out_srs="EPSG:2959+6647" --writers.las.scale_x=0.01 --writers.las.scale_y=0.01 --writers.las.scale_z=0.001 --verbose "Debug5"

Warning 1: Cannot find pcs.csv
Warning 1: Cannot find gcs.csv
Warning 1: Cannot find datum.csv or gdal_datum.csv
(pdal translate filters.reprojection Debug) GDAL debug: OGRCT: PROJ >= 4.8.0 features enabled
(pdal translate filters.reprojection Debug) GDAL debug: OGRCT: Using locale-safe proj version
(pdal translate filters.reprojection Debug) GDAL debug: OGRCT: Source: +proj=tmerc +lat_0=0 +lon_0=-76.5 +k=0.9999 +x_0=304800 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +geoidgrids=HT2_0.gtx +vunits=m +no_defs
(pdal translate filters.reprojection Debug) GDAL debug: OGRCT: Target: +proj=utm +zone=18 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +geoidgrids=CGG2013n83a.gtx +vunits=m +no_defs
pj_open_lib(HT2_0.gtx): call fopen(/fs/ssm/nrcan/geobase/elevation-201801/proj_4.9.3_ubuntu-14.04-amd64-64/share/proj/HT2_0.gtx) - succeeded

GTX 2820x1290: LL=(-141.983333,41.0166667) UR=(-48.0166667,83.9833333)
pj_open_lib(HT2_0.gtx): call fopen(/fs/ssm/nrcan/geobase/elevation-201801/proj_4.9.3_ubuntu-14.04-amd64-64/share/proj/HT2_0.gtx) - succeeded

pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_open_lib(CGG2013n83a.gtx): call fopen(/fs/ssm/nrcan/geobase/elevation-201801/proj_4.9.3_ubuntu-14.04-amd64-64/share/proj/CGG2013n83a.gtx) - succeeded

GTX 4800x2400: LL=(-169.983333,10.0166667) UR=(-10.0166667,89.9833333)
pj_open_lib(CGG2013n83a.gtx): call fopen(/fs/ssm/nrcan/geobase/elevation-201801/proj_4.9.3_ubuntu-14.04-amd64-64/share/proj/CGG2013n83a.gtx) - succeeded

pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
pj_apply_gridshift(): used GTX Vertical Grid Shift File
(pdal translate writers.las Debug) Wrote 241117 points to the LAS file
(pdal translate Debug) GDAL debug: GDAL: In GDALDestroy - unloading GDAL shared library.
```

Is there additional environment variables that would need to be set in order to have PDAL commands not issuing these warnings.

**Comment by hobu** [comment] 2018-01-04 16:16
Can you post `input.laz` somewhere so we can work to replicate? Does our Docker container exhibit the same issue?

I suspect there is some GDAL debug output that we are not capturing appropriately. I think the `Warning 1: Cannot find pcs.csv` is a PROJ warning that happens on PROJ wakeup., and we need to be capturing that warning stream too somehow.

**Comment by jfbourgon** [comment] 2018-01-04 17:24
I uploaded two LAZ input files coming from two distinct providers into the following web folder: http://ftp.maps.canada.ca/pub/nrcan_rncan/data_access/pdal/

Here are the `pdal translate` commands I used for each of them (source and destination horizontal srs are distinct) :
```
pdal translate ~/input-1.laz ~/output-1.laz reprojection --filters.reprojection.in_srs="EPSG:2951+5713" --filters.reprojection.out_srs="EPSG:2959+6647" --writers.las.scale_x=0.01 --writers.las.scale_y=0.01 --writers.las.scale_z=0.001

pdal translate ~/input-2.laz ~/output-2.laz reprojection --filters.reprojection.in_srs="EPSG:2953+5713" --filters.reprojection.out_srs="EPSG:2960+6647" --writers.las.scale_x=0.01 --writers.las.scale_y=0.01 --writers.las.scale_z=0.001
```
Interestingly, I only getting the warnings for the first file (input-1.laz).

**Comment by abellgithub** [comment] 2018-01-05 13:44
I'm unable to reproduce this with GDAL 2.1 and current PDAL trunk.

**Comment by jfbourgon** [comment] 2018-01-05 21:28
I'm currentIy using GDAL 2.2.3 but also have access to 2.1. I will test with this version instead and see if the behaviour change.

**Comment by abellgithub** [comment] 2018-02-13 14:48
@jfbourgon: Did you resolve this?  If so, I'd like to close this issue.

**Comment by jfbourgon** [comment] 2018-02-13 14:54
I'm still getting warnings with some LAS files but as suggested it may be related to the way GDAL was installed on my system. I was wondering which kind of PROJ/GDAL warnings could be related to PDAL warning ```Warning 1: Cannot find pcs.csv```

**Comment by neteler** [comment] 2018-08-28 07:53
We face the same issue in an Ubuntu based docker. Right now I don't know how to debug that.

**Comment by hobu** [comment] 2018-08-28 16:29
```
Warning 1: Cannot find datum.csv or gdal_datum.csv
Warning 1: Cannot find ellipsoid.csv
```

I've been seeing this bug too (especially in Conda). I haven't had time to run it down, but I hope to soon.

**Comment by abellgithub** [comment] 2018-11-30 17:12
@hobu: Didn't we decide this was a GDAL build issue?

**Comment by hobu** [comment] 2018-11-30 17:13
It is https://github.com/conda-forge/geotiff-feedstock/pull/8 which should be picked up by the next refreshes of GDAL/PDAL in the conda environment.

**Closed** 2019-05-21 18:20 UTC
