### ISSUE TITLE
pdal ground with -classify broken

### ISSUE THREAD

**Issue by matthewhanson** [PDAL/PDAL#944] opened 2015-06-22 17:30 UTC
pdal ground seems to have broken somewhere in the last 6 weeks.

Using
'pdal ground -i infile.las -i outfile.las --classify'

Should create an output file with all the original points, but ground points labeled.   Instead it creates an output file that is the same, with no points labeled as ground.

I had it running properly on another machine, so I reverted to the same commit (May 9), and it works with that build.     I can do some more digging to see when it exactly broke, but I wanted to post the issue as I thought the devs could probably narrow down when the problem was caused (or perhaps, the behavior has changed and I'm calling it incorrectly).

Also, when running even with -v4, it generates no errors or additional information, so it seems to run successfully.

**Comment by chambbj** [comment] 2015-06-22 17:43
Matt,

The intended behavior has not changed. I'll take a peak to see if I can
pinpoint where we regressed.

Brad

**Comment by chambbj** [comment] 2015-06-22 18:26
@matthewhanson Found it. Fix coming shortly.

**Comment by chambbj** [comment] 2015-06-22 18:30
@matthewhanson Perhaps I closed this prematurely. Can you pull from master and verify the fix on your end?

**Closed** 2015-06-22 18:30 UTC

**Comment by matthewhanson** [comment] 2015-06-22 18:37
Thanks Brad...yes, compiling now to test and will report back.

**Comment by matthewhanson** [comment] 2015-06-22 20:00
This works now, thanks so much for quickly remedying it!
