### ISSUE TITLE
writers.gdal can not find custom dimension with an underscore in it's name

### ISSUE THREAD

**Issue by kbevers** [PDAL/PDAL#1378] opened 2016-11-11 09:58 UTC
It would seem that the writers.gdal drivers has problems understanding dimensions with an underscore in the name.  I get an error when trying to grid a LAS1.4 file with Riegls extrabytes that has a custom dimension called ```pulse_with```:
```
> pdal pipeline grid_pipe.json
PDAL: Dimension name is not known!
```
I get no error when the dimension is created as ```pulsewidth```.  

grid_pipe.json looks like this:
```
{
  "pipeline":[
    {
        "type": "readers.las",
        "filename": "C:\\data\\lidar_waveforms\\new_dataset\\out\\extrabites_new2.las"
    },
    {
        "type": "writers.gdal",
        "resolution": 2,
        "radius": 2.7,
        "filename": "outputfile.tif",
        "dimension": "pulse_width",
        "output_type": "mean"
    }
  ]
}
```

and the file is a LAS1.3 with the Riegl extrabytes translated to a LAS1.4 (so that PDAL knows that the extra dimensions are there):

```
pdal translate -i extrabites_new.las -o out\extrabites_new2.las --readers.las.extra_dims="amplitude=uint16,pulse_width=uint16" --writers.las.forward=vlr --writers.las.extra_dims=all --writers.las.minor_version=4
```

Since the dimension ```pulse_width``` can be created I assume that dimensions with underscores (and possibly other special characters) are allowed.

**Comment by kbevers** [comment] 2016-11-11 10:21
By the way, this is on Windows. Build with vs2015 from master. If needed I'm happy to supply a test file.

**Comment by abellgithub** [comment] 2016-11-11 14:31
Essentially a duplicate of #1379

**Closed by abellgithub** 2016-11-11 14:31 UTC
