### ISSUE TITLE
Pdal import failure- DLL load failed

### ISSUE THREAD

**Issue by tanisha11** [PDAL/PDAL#2299] opened 2018-12-06 13:19 UTC
After creating a new conda virtual environment and installing pdal and python-pdal with conda install -c conda-forge pdal python-pdal, importing pdal fails giving the following error:

from pdal import libpdalpython
ImportError: DLL load failed: The specified module could not be found.

The module is present within the pdal package yet it fails.

**Comment by tanisha11** [comment] 2018-12-12 08:39
On further testing, it was noticed that libtiff.dll is not being downloaded into the bin folder when pdal is installed using conda-forge.

**Comment by abellgithub** [comment] 2018-12-12 13:41
The library name of libtiff was changed on conda-forge for Windows, breaking PDAL's conda recipe, among others.  We're trying to get the powers that be to make the necessary modifications to make this work again.

**Comment by hobu** [comment] 2018-12-12 20:33
This issue should be fixed upstream in conda now. If you can please update your conda packages and test, things should work. Reopen if you still have trouble.

**Closed by hobu** 2018-12-12 20:33 UTC

**Comment by conlin-matt** [comment] 2019-11-17 14:05
Hi @hobu. Thanks for putting together such a useful package; PDAL has been invaluable to me over the last few months. I am trying to migrate a program of mine to another system. The new system is a Windows 10 64-bit. On a fresh install of Anaconda (64-bit), after conda creating a new env with Python 3.6 and running `conda install -c conda-forge pdal python-pdal gdal`, trying to `import pdal` in Python gives me the same error as the OP. Full error log is as follows:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\x\Anaconda3\envs\SurfRCaT_env\lib\site-packages\pdal\__init__.py", line 3, in <module>
    from .pipeline import Pipeline
  File "C:\Users\x\Anaconda3\envs\SurfRCaT_env\lib\site-packages\pdal\pipeline.py", line 2, in <module>
    from pdal import libpdalpython
ImportError: DLL load failed: The specified module could not be found.

I also get dll errors when trying to run pdal from the command line, specifically regarding `ucrtbased.dll` and `VCRUNTIME140D.dll`. I can't seem to figure this out- any idea what the problem(s) might be?

**Comment by hobu** [comment] 2019-11-17 22:02
> I also get dll errors when trying to run pdal from the command line, specifically regarding ucrtbased.dll and VCRUNTIME140D.dll. I can't seem to figure this out- any idea what the problem(s) might be?

Not your fault. Something in the conda chain is linked against the debug runtime. I have bumped the build number of the python-pdal conda-forge package, and I hope this will cure the issue. Track https://github.com/conda-forge/python-pdal-feedstock/pull/29

**Comment by conlin-matt** [comment] 2019-11-18 16:17
That did the trick. Thanks so much for the prompt reply and assistance.

**Comment by raineyracecar** [comment] 2021-05-19 12:59
Hi @hobu, I too ran into the same problem as @conlin-matt for pdal v2.2.0. Tried importing pdal into ArcGIS Pro (2.6.3) python window after running conda install -c conda-forge pdal python-pdal gdal, and received the exact same error @conlin-matt did.

Is this possible the same issue? Thanks for your help :)

**Comment by raineyracecar** [comment] 2021-05-19 13:05
![image](https://user-images.githubusercontent.com/84454562/118817422-cf64ad00-b878-11eb-841f-c1a305aa4f68.png)

Above is the python error I received. Will try running it via cmd to see if a specific dll is missing. Thanks so much for your quick response!

**Comment by WalidGharianiEAGLE** [comment] 2021-05-20 11:50
Im also getting the same error message when trying to import pdal.

I also noticed that when I tested an example pipeline provided here https://pdal.io/pipeline.html to generate a DTM. it works only with the `"filters.smrf"` but if I change it with `"filters.smrf"` I get the foloowing `PDAL: Couldn't create filter stage of type 'filters.csf'.You probably have a version of PDAL that didn't come with a plugin you're trying to load.  Please see the FAQ at https://pdal.io/faq` 

`pdal version: 2.4.0` installed with `conda-forge`

**Comment by raineyracecar** [comment] 2021-05-20 16:56
@hobu and others...For now got pdal 2.2.0 to import into ArcGIS Pro 2.6.2 by first copying its Python environment (arcgispro-py3), pasting it into Conda envs and activating it in the Anaconda command prompt (i.e. activate myenv), installing pdal to the copied/cloned environment (i.e. conda install -c conda-forge pdal python-pdal gdal), and then adding again to ArcGIS Pro 2.6.2 under Settings (https://pro.arcgis.com/en/pro-app/latest/arcpy/get-started/work-with-python-environments.htm). I'm sure there's another way to do it...but so far it's working?

**Comment by WalidGharianiEAGLE** [comment] 2021-05-20 19:21
@raineyracecar Im actually not using pdal withing ArcGIS, so your case is specific. I just need to write and run scripts with python. Also the official installation of pdal with conda is as follow: https://anaconda.org/conda-forge/python-pdal so im not sure form where does this suggestion of using `conda install -c conda-forge pdal python-pdal gdal` comes in place.

**Comment by raineyracecar** [comment] 2021-05-21 19:33
Hi @WalidGharianiEAGLE, there's a few ways to obtain pdal as per https://pdal.io/download.html. I used the Conda approach, which is where conda install -c conda-forge pdal python-pdal gdal, came from. You are correct though that pdal can also be obtained from https://anaconda.org/conda-forge/python-pdal. 

pip install pdal (in conda)

will get you v. 2.4.0, but unfortunately I'm working with firewalls that prohibit me from completing installing that version. I will admit that though I was able to bring pdal into the Python environment in ArcGIS Pro, I could not run it using the Python shell in Conda...not sure what might be happening there. I also have not tried running python from cmd, IDLE, PyCharm or other IDEs/shells.

**Comment by KathiXIII** [comment] 2021-06-01 14:12
I have just installed pdal in conda using  `conda install -c conda-forge pdal python-pdal gdal` .

Still, importing pdal in python fails:

> from pdal import libpdalpython
> ImportError: libpdal_base.so.12: cannot open shared object file: No such file or directory

I guess it is a similar issue.

**Comment by hobu** [comment] 2021-06-01 14:18
Confirmed. We need to rerender the PDAL Python package feedstock.

**Comment by hobu** [comment] 2021-06-01 15:27
Please try again with a new environment. It should be working now.

**Comment by encsbalazs** [comment] 2022-01-13 12:51
I installed the pdal with "pip install pdal" to my Python 3.9 venv and got the same error : 
**DLL load failed while importing libpdalpython: The specified module could not be found.**
What can i do with this? 
Thanks

**Comment by dkeatin2** [comment] 2022-03-17 21:18
Looks like this might be happening again. 
I installed into a new environment with `conda install -c conda-forge pdal python-pdal pdal`  activated it, and get ` ImportError: DLL load failed while importing libpdalpython: The specified module could not be found. ` trying to import pdal in python.

**Comment by lobnico** [comment] 2023-01-24 09:39
bump

**Comment by theodorehreuter** [comment] 2023-03-31 21:14
happening again 
`miniconda3/envs/lidar_pdal9/lib/python3.9/site-packages/pdal/__init__.py", line 4, in <module>
    from . import libpdalpython
ImportError: libLerc.so.4: cannot open shared object file: No such file or directory`

**Comment by guillochon** [comment] 2023-06-26 20:01
Happening to me too

**Comment by network-mapping-dev** [comment] 2023-07-26 21:15
This is happening to me - installing via conda

**Comment by eprior316** [comment] 2023-09-18 17:52
Happening to me too.

**Comment by hobu** [comment] 2024-04-22 15:56
I'm currently working this issue. It is unfortunately complicated due to how conda packages things but I hope something is available to test at the end of the week.

**Comment by finnp-sogelink** [comment] 2024-07-02 08:43
Had this same problem when importing pdal into my notebook in VSCode. After days of debugging my Conda environment I found out my environment works fine, but the import works ONLY if pdal is the first package imported. I am running the newest version of python-pdal (3.4.5) and python (3.12.4).
```
import pdal
import foo
import bar
...
```

**Comment by hobu** [comment] 2024-07-04 15:27
> the import works ONLY if pdal is the first package imported

Which platform? Can you open a new ticket in https://github.com/PDAL/python/ providing details?
