### ISSUE TITLE
1.8 regression with "Input PointView does not have any points classified as ground"

### ISSUE THREAD

**Issue by luipir** [PDAL/PDAL#2287] opened 2018-11-28 19:21 UTC
after upgrade from 1.7.2 to 1.8 a specific pipeline started to fail for some specific las files. Not all las fails.
back to 1.7 or 1.6 the problem disappear.

here the las file (remove the tailing .txt):
[OUTPUT_PCL.laz.txt](https://github.com/PDAL/PDAL/files/2626443/OUTPUT_PCL.laz.txt)

and the pipeline (remove the tailing .txt):
[3_a_Improve_ground_and_not_ground_by_normals.json.txt](https://github.com/PDAL/PDAL/files/2626271/3_a_Improve_ground_and_not_ground_by_normals.json.txt)

the command:
pdal pipeline --verbose=8 -i /path/to/3_a_Improve_ground_and_not_ground_by_normals.json --readers.las.filename=/path/to/OUTPUT_PCL.laz --writers.las.filename=/path/to/out.las

fail only with 1.8 (on win, linux and linux with bionic with compiled pdal)

fail almost at the end trying to calc hug

any hint to debug other then gdb?

**Comment by abellgithub** [comment] 2018-11-28 19:29
This is a duplicate of #2275.  It has been fixed in the 1.8-maintenance branch.

**Comment by abellgithub** [comment] 2018-11-28 19:56
I can't unzip the LAZ file you've attached.

**Comment by luipir** [comment] 2018-11-28 20:06
sorry I wrongly renames .zip... was .txt, just remove extension and use directly the laz. Because github does not accept any file extension for the attachments

**Comment by luipir** [comment] 2018-11-28 20:14
> I wrongly renames .zip... was .txt

renamed as OUTPUT_PCL.laz.txt

**Comment by abellgithub** [comment] 2018-11-28 20:19
I get:

`(pdal) master $ bin/pdal pipeline 2287.json
PDAL: filters.hag: Input PointView does not have any points classified as ground`

Excerpt from `pdal info`:
```

**Comment by luipir** [comment] 2018-11-28 20:24
@abellgithub hag filter is only last step of processing, this pipeline is used in "production" and does not enerate any error with oter similar las. The error does not appear with the same las with old pdal versions.

**Comment by abellgithub** [comment] 2018-11-28 21:51
A change in stage execution broke this behavior.  We don't formally support diamond-shaped pipelines (see #1537), of which this is an example.

That said, we did execute many of them properly (yours included) in former releases.  I'll try to come up with a fix.

I've rewritten your pipeline to eliminate this construction.  I realize this isn't terribly satisfying.  Here's the updated pipeline: [2287.json.txt](https://github.com/PDAL/PDAL/files/2626694/2287.json.txt)

**Comment by luipir** [comment] 2018-11-28 21:57
//  Select points with classification=2 (ground)
    //  We want apply normals filter on ground points only
    {
        "type":"filters.range",
        "limits":"Classification[2:2]", <--- would be [1:1] ?????????
        "inputs":"all_points1",
        "tag":"groundrange1"
    },
    {
        "type":"filters.range",
        "limits":"Classification[2:2]",
        "inputs":"all_points2",
        "tag":"groundrange2"
    },

**Comment by luipir** [comment] 2018-11-28 21:59
> We don't formally support diamond-shaped pipelines (see #1537),

Ho! I see the logic of #1537! I didn't realized this "best" practice to write pipelines

**Comment by abellgithub** [comment] 2018-11-28 22:01
I just made a copy of the ground range filter and named then groundrange1 and groundrange2 - I think it's correct, but you should look it over.  I certainly may have errored.

**Comment by luipir** [comment] 2018-11-28 22:11
sure, no problem, I asked to be sure I understood the diamond concept, tnx.
I'll review all pipelines to avoid diamonds... do you mind it's better to avoid diamond only in case of errors or always? or can generate unexpected results? sorry I'm more focused on qgis and I never deeply dig into pdal code... btw thanks for point it out the problem.

**Comment by abellgithub** [comment] 2018-11-28 22:17
In previous releases, diamonds worked by making copies of stages that were shared as a root.  This is not what people probably expect -- reading files multiple times isn't usually desired -- but it generally worked.

But I'd like it to work as it did in previous releases.  I may have it fixed by the end of the week so that it behaves like before.  If you're building yourself or using docker, you should be able to get back to where you were when this ticket is closed.

**Comment by abellgithub** [comment] 2018-11-29 16:52
Closing in favor of #2290

**Closed by abellgithub** 2018-11-29 16:52 UTC
