### ISSUE TITLE
pdal.ground kernel is broken (PDAL 1.5)

### ISSUE THREAD

**Issue by pierotofy** [PDAL/PDAL#1610] opened 2017-06-20 17:23 UTC
From PDAL 1.5 (docker):

```
pdal ground -i anyfile.las -o out.las
PDAL: filters.pmf: Unexpected argument 'classify'.
```

I think a fix might be as simple as removing the classify parameter here: https://github.com/PDAL/PDAL/blob/master/kernels/GroundKernel.cpp#L83

But that might change the original behavior of the ground command, so perhaps there's a better solution.

**Comment by chambbj** [comment] 2017-06-20 17:28
Duplicate of #1578. Thought I'd fixed this. Will check.

**Comment by chambbj** [comment] 2017-06-20 17:43
@pierotofy Yep, had this in a branch and just never closed the loop on it. Assuming is passes all checks, I'll merge into master shortly. If you want to grab and build right away, it can be found here https://github.com/PDAL/PDAL/tree/issue/1578-ground-kernel.

**Comment by hobu** [comment] 2017-06-20 17:46
Please merge this back to the `1.5-maintenance` too, which will force a regeneration of the docker images

**Comment by pierotofy** [comment] 2017-06-20 18:07
Thanks for looking into this so quickly!

One quick question about the `--classify` parameter: the docs said that using this parameter used to "Apply classification labels?". If I have an existing script that uses the --classify parameter is it safe to simply remove it?

**Comment by chambbj** [comment] 2017-06-20 18:10
Yes, you must remove it (as you have already seen!). But rest assured, if you need the classifications, they will still be there as long as `extract=false`.

**Comment by pierotofy** [comment] 2017-06-20 18:10
Fantastic, thank you!

**Closed** 2017-06-20 18:23 UTC

**Comment by chambbj** [comment] 2017-06-20 18:33
@pierotofy `pdal/pdal:1.5` is rebuilding (https://hub.docker.com/r/pdal/pdal/builds/). May want to check on it in an hour or so. Let us know if you have any more issues.
