### ISSUE TITLE
Bad VLR offset test for compressed LAS files (LAZ)

### ISSUE THREAD

**Issue by sorenrasmussenai** [PDAL/PDAL#3348] opened 2021-02-02 13:07 UTC
**Symptoms:**
When I try to read a LAZ file, I get the following error:
`PDAL: readers.las: Invalid extended VLR offset - exceeds file size.`
If I unzip it first using `laszip`, and read the resulting LAS file, it works.

**Possible fix?**
I suspect the source of the error is [here](https://github.com/PDAL/PDAL/blob/c845a9418785ead1821a940961c0a0be1a88e859/io/LasReader.cpp#L197) and [here](https://github.com/PDAL/PDAL/blob/c845a9418785ead1821a940961c0a0be1a88e859/io/LasHeader.cpp#L402), where the file size is tested.
For the LAZ file, `m_fileSize` should probably be the size of the unzipped data, rather than the actual size of the zipped file..

**Details:**

pdal 2.3.0 (git-version: b7aaa4)
`"pipeline": [
        {
            "type": "readers.las",
            "filename": "test.las"
        }
      ] `

**Comment by abellgithub** [comment] 2021-02-02 13:33
:(

Sorry about this. Will be fixed today.

**Comment by abellgithub** [comment] 2021-02-02 14:04
At first I thought this was an obvious bug, but now I don't think so. How was your file created?

**Comment by sorenrasmussenai** [comment] 2021-02-02 14:34
> At first I thought this was an obvious bug, but now I don't think so. How was your file created?

They are freely available from a Danish government agency [here](https://download.kortforsyningen.dk/content/dhmpunktsky).
(It's in Danish and you have to create a user to download them - sorry)

**lasinfo output**
```
lasinfo (210117) report for 'test.laz'
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             0
  global_encoding:            16
  project ID GUID data 1-4:   00000000-0000-0000-0000-000000000000
  version major.minor:        1.4
  system identifier:          'PDAL'
  generating software:        'PDAL 1.3.0 (a997e7)'
  file creation day/year:     358/2016
  header size:                375
  offset to point data:       2923
  number var. length records: 3
  point data format:          6
  point data record length:   36
  number of point records:    15332131
  number of points by return: 12391302 1253653 856229 547948 282999
  scale factor x y z:         0.01 0.01 0.01
  offset x y z:               0 0 0
  min x y z:                  570000.00 6210000.00 -30.65
  max x y z:                  571000.00 6211000.00 162.64
WARNING: stored resolution of min_z not compatible with z_offset and z_scale_factor: -30.648977524296505
WARNING: stored resolution of max_z not compatible with z_offset and z_scale_factor: 162.643903010582335
  start of waveform data packet record: 0
  start of first extended variable length record: 551959639
  number of extended_variable length records: 0
  extended number of point records: 15332131
  extended number of points by return: 12391302 1253653 856229 547948 282999 0 0 0 0 0 0 0 0 0 0
variable length header record 1 of 3:
  reserved             0
  user ID              'LASF_Spec'
  record ID            4
  length after header  576
  description          'Extra Bytes Record'
    Extra Byte Descriptions
      data type: 3 (unsigned short), name "Red", description: "Red image channel value", scale: 1 (not set), offset: 0 (not set)
      data type: 3 (unsigned short), name "Green", description: "Green image channel value", scale: 1 (not set), offset: 0 (not set)
      data type: 3 (unsigned short), name "Blue", description: "Blue image channel value", scale: 1 (not set), offset: 0 (not set)
variable length header record 2 of 3:
  reserved             0
  user ID              'LASF_Projection'
  record ID            2112
  length after header  905
  description          'OGC Transformation Record'
    WKT OGC COORDINATE SYSTEM:
    COMPD_CS["ETRS89 / UTM zone 32N + DVR90 height",PROJCS["ETRS89 / UTM zone 32N",GEOGCS["ETRS89",DATUM["European_Terrestrial_Reference_System_1989",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6258"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4258"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",9],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","25832"]],VERT_CS["DVR90 height",VERT_DATUM["Dansk Vertikal Reference 1990",2005,AUTHORITY["EPSG","5206"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Gravity-related height",UP],AUTHORITY["EPSG","5799"]],AUTHORITY["EPSG","7416"]]
variable length header record 3 of 3:
  reserved             0
  user ID              'liblas'
  record ID            2112
  length after header  905
  description          'OGR variant of OpenGIS WKT SRS'
LASzip compression (version 3.1r0 c3 50000): POINT14 3 BYTE14 3
reporting minimum and maximum for all LAS point record entries ...
  X            57000000   57100000
  Y           621000000  621100000
  Z               -3065      16264
  intensity           0      65502
  return_number       1          5
  number_of_returns   1          5
  edge_of_flight_line 0          1
  scan_direction_flag 0          0
  classification      1         20
  scan_angle_rank   -32         31
  user_data           2          2
  point_source_ID  5275      64275
  gps_time 114622667.607341 114918422.109834
WARNING: range violates GPS week time specified by global encoding bit 0
  extended_return_number          1      5
  extended_number_of_returns      1      5
  extended_classification         1     20
  extended_scan_angle         -5333   5167
  extended_scanner_channel        0      0
  attribute0          0      65280  ('Red')
  attribute1          0      65280  ('Green')
  attribute2          0      65280  ('Blue')
number of first returns:        12391302
number of intermediate returns: 1687018
number of last returns:         12391781
number of single returns:       11137970
WARNING: point type is 6 but (legacy) number of point records in header is 15332131 instead zero.
WARNING: point type is 6 but (legacy) number of points by return [1] in header is 12391302 instead zero.
WARNING: point type is 6 but (legacy) number of points by return [2] in header is 1253653 instead zero.
WARNING: point type is 6 but (legacy) number of points by return [3] in header is 856229 instead zero.
WARNING: point type is 6 but (legacy) number of points by return [4] in header is 547948 instead zero.
WARNING: point type is 6 but (legacy) number of points by return [5] in header is 282999 instead zero.
overview over extended number of returns of given pulse: 11137970 794782 924874 1059695 1414810 0 0 0 0 0 0 0 0 0 0
histogram of classification of points:
            7491  unclassified (1)
        11489061  ground (2)
          253493  low vegetation (3)
          447394  medium vegetation (4)
         2856703  high vegetation (5)
          118812  building (6)
            5337  noise (7)
           66963  water (9)
           43365  wire conductor (14)
              87  Reserved for ASPRS Definition (18)
           41709  Reserved for ASPRS Definition (19)
            1716  Reserved for ASPRS Definition (20)
```

**Comment by sorenrasmussenai** [comment] 2021-02-02 14:44
@abellgithub 
You should be getting an email in 5 minutes with a pair of las/laz files :)

**Comment by abellgithub** [comment] 2021-02-02 14:56
This is caused by a bug in PDAL before version 2.1 where files were written without an EVLR offset: https://github.com/PDAL/PDAL/issues/2824

**Comment by sorenrasmussenai** [comment] 2021-02-02 15:01
I get the error with non-public data from TerraScan also:

```
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             0
  global_encoding:            17
  project ID GUID data 1-4:   00000000-0000-0000-0000-000000000000
  version major.minor:        1.4
  system identifier:          ''
  generating software:        'TerraScan'
  file creation day/year:     306/2018
  header size:                375
  offset to point data:       2923
  number var. length records: 3
  point data format:          6
  point data record length:   47
  number of point records:    13638492
  number of points by return: 11035806 1492575 703863 293893 89570
  scale factor x y z:         0.001 0.001 0.001
  offset x y z:               0 5000000 0
  min x y z:                  689000.000 6051000.000 -166.602
  max x y z:                  689999.999 6051999.999 180.775
WARNING: stored resolution of min_z not compatible with z_offset and z_scale_factor: -166.601781481008913
WARNING: stored resolution of max_z not compatible with z_offset and z_scale_factor: 180.774505751077925
  start of waveform data packet record: 0
  start of first extended variable length record: 641012047
  number of extended_variable length records: 0
  extended number of point records: 13638492
  extended number of points by return: 11035806 1492575 703863 293893 89570 19471 2989 304 19 2 0 0 0 0 0
variable length header record 1 of 3:
  reserved             0
  user ID              'LASF_Spec'
  record ID            4
  length after header  576
  description          'Extra Bytes Record'
    Extra Byte Descriptions
      data type: 1 (unsigned char), name "ClassFlags", description: "Class Flags", scale: 1 (not set), offset: 0 (not set)
      data type: 10 (double), name "Amplitude", description: "This is the ratio of the receive", scale: 1 (not set), offset: 0 (not set)
      data type: 10 (double), name "Pulse width", description: "", scale: 1 (not set), offset: 0 (not set)
variable length header record 2 of 3:
  reserved             0
  user ID              'LASF_Projection'
  record ID            2112
  length after header  905
  description          'OGC Transformation Record'
    WKT OGC COORDINATE SYSTEM:
    COMPD_CS["ETRS89 / UTM zone 32N + DVR90 height",PROJCS["ETRS89 / UTM zone 32N",GEOGCS["ETRS89",DATUM["European_Terrestrial_Reference_System_1989",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6258"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4258"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",9],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","25832"]],VERT_CS["DVR90 height",VERT_DATUM["Dansk Vertikal Reference 1990",2005,AUTHORITY["EPSG","5206"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Gravity-related height",UP],AUTHORITY["EPSG","5799"]],AUTHORITY["EPSG","7416"]]
variable length header record 3 of 3:
  reserved             0
  user ID              'liblas'
  record ID            2112
  length after header  905
  description          'OGR variant of OpenGIS WKT SRS'
LASzip compression (version 3.1r0 c3 50000): POINT14 3 BYTE14 3
reporting minimum and maximum for all LAS point record entries ...
  X           689000000  689999999
  Y          1051000000 1051999999
  Z             -166602     180775
  intensity           7      32767
  return_number       1          7
  number_of_returns   1          7
  edge_of_flight_line 0          1
  scan_direction_flag 0          1
  classification      0         18
  scan_angle_rank   -29         23
  user_data           1          2
  point_source_ID 14002      14003
  gps_time 209547656.720765 209547892.764223
  extended_return_number          1     10
  extended_number_of_returns      1     10
  extended_classification         1    200
  extended_scan_angle         -4866   3865
  extended_scanner_channel        0      1
  attribute0          0          0  ('ClassFlags')
  attribute1          0       36.7  ('Amplitude')
  attribute2          0       2.52  ('Pulse width')
WARNING: 1 points outside of header bounding box
number of first returns:        11035806
number of intermediate returns: 1110929
number of last returns:         11034139
number of single returns:       9542382
WARNING: point type is 6 but (legacy) number of point records in header is 13638492 instead zero.
WARNING: point type is 6 but (legacy) number of points by return [1] in header is 11035806 instead zero.
WARNING: point type is 6 but (legacy) number of points by return [2] in header is 1492575 instead zero.
WARNING: point type is 6 but (legacy) number of points by return [3] in header is 703863 instead zero.
WARNING: point type is 6 but (legacy) number of points by return [4] in header is 293893 instead zero.
WARNING: point type is 6 but (legacy) number of points by return [5] in header is 89570 instead zero.
overview over extended number of returns of given pulse: 9542382 1576861 1230121 817910 350951 99005 18803 2286 153 20 0 0 0 0 0
histogram of classification of points:
           19217  unclassified (1)
         8342112  ground (2)
          218795  low vegetation (3)
          939579  medium vegetation (4)
         2475264  high vegetation (5)
         1102842  building (6)
            2309  noise (7)
          144787  keypoint (8)
          368255  water (9)
           13551  bridge deck (17)
            1373  Reserved for ASPRS Definition (18)
histogram of extended classification of points:
           10408  extended classification (200)
WARNING: real max z larger than header max z by 0.000494
```

**Comment by abellgithub** [comment] 2021-02-02 15:02
I'd need a terra scan file to examine.

**Comment by sorenrasmussenai** [comment] 2021-02-02 15:08
I'll see what I can do

**Closed** 2021-04-09 23:28 UTC
