### ISSUE TITLE
Reading ept with v2.2 causes error, but not in v2.1

### ISSUE THREAD

**Issue by mantbe** [PDAL/PDAL#3400] opened 2021-04-01 21:49 UTC
**Describe the bug**
When reading a USGS 3DEP ept file using PDAL 2.2.0 I get the following error: "PDAL: Can't create dimension with invalid name 'Pulse width'.".  I get this error when running PDAL in docker or in a fresh conda environment (using pdal v 2.2.0 in both).  I do not get this error when running PDAL v 2.1.0. in a conda environment, and the job runs successfully. 

```
$ pdal pipeline pipeline.json
```

<details>
  
```
{
    "pipeline": [{
        "type": "readers.ept",
        "filename": "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MI_BranchCo_2017_LAS_2019/ept.json",
        "bounds": "([-9483250.683171479, -9476065.602512673], [5124739.6706367135,5130376.9014727445])"
    },    {
        "type": "filters.range",
        "limits":"Classification[2:2]"
    },
    {
        "type":"filters.reprojection",
        "in_srs":"EPSG:3857",
        "out_srs":"EPSG:26916"
    },{
        "type" : "writers.las",
        "filename": "points.las",
        "a_srs": "EPSG:26916"
    }]}

```

</details>

**Expected behavior**
I would expect PDAL v2.2.0 to be able to read the ept.json since the previous version reads the same file without error.

**System/installation information:**

```
$ Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64 x86_64
```

```
$ pdal 2.2.0 (git-version: Release)
```

<details>
  
```
# Name                    Version                   Build  Channel
boost-cpp                 1.74.0               h43a636a_2    conda-forge
bzip2                     1.0.8                hc929b4f_4    conda-forge
c-ares                    1.17.1               h0d85af4_1    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
cairo                     1.16.0            he43a7df_1008    conda-forge
certifi                   2020.12.5        py39h6e9494a_1    conda-forge
cfitsio                   3.470                h01dc385_7    conda-forge
curl                      7.76.0               h06286d4_0    conda-forge
expat                     2.3.0                he49afe7_0    conda-forge
fontconfig                2.13.1            hd23ceaa_1004    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
freexl                    1.0.6                h0d85af4_0    conda-forge
geos                      3.9.1                he49afe7_2    conda-forge
geotiff                   1.6.0                hba2ba3e_5    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
hdf4                      4.2.13            h71d84a9_1004    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
json-c                    0.15                 hcb556a6_0    conda-forge
jsoncpp                   1.9.4                h926bf3e_1    conda-forge
kealib                    1.4.14               h31dd65d_2    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
laszip                    3.4.3                h4a8c4bd_1    conda-forge
laz-perf                  1.5.0                hb1e8313_0    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.76.0               h8ef9fac_0    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libdap4                   3.20.6               h3e144a0_2    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgdal                   3.2.2                hc84532a_2    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_21    conda-forge
libgfortran5              9.3.0               h6c81a4c_21    conda-forge
libglib                   2.68.0               hd556434_2    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h8fd9edb_1013    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libnetcdf                 4.7.4           nompi_h9d8a93f_107    conda-forge
libnghttp2                1.43.0               h07e645a_0    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     13.1                 h052a64a_2    conda-forge
librttopo                 1.1.0                h5413771_6    conda-forge
libspatialite             5.0.1                heb715ac_4    conda-forge
libssh2                   1.9.0                h52ee1ee_6    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libwebp-base              1.2.0                h0d85af4_2    conda-forge
libxml2                   2.9.10               h802ca4f_3    conda-forge
llvm-openmp               11.1.0               hda6cdc1_0    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
nitro                     2.7.dev6             h4a8c4bd_3    conda-forge
numpy                     1.20.2           py39h7eed0ac_0    conda-forge
openjpeg                  2.4.0                h6cbf5cd_0    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pdal                      2.2.0                h1c6fe43_7    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
poppler                   21.03.0              h640f9a4_0    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.1                 ha63e576_2    conda-forge
proj                      8.0.0                h1512c50_0    conda-forge
python                    3.9.2           h2502468_0_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
setuptools                49.6.0           py39h6e9494a_3    conda-forge
sqlite                    3.35.3               h44b9ce1_0    conda-forge
tiledb                    2.2.7                he9a4fb4_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tzcode                    2021a                h0d85af4_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xerces-c                  3.2.3                h379762d_2    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.9                h582d3a0_0    conda-forge
```

</details>

<details>
  
```
active environment : pdal220
shell level : 3
populated config files : 
conda version : 4.9.2
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __osx=10.13.6=0
                          __unix=0=0
                          __archspec=1=x86_64
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.7.7 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

</details>

**Comment by abellgithub** [comment] 2021-04-01 21:52
This is a duplicate of #3325

**Comment by mantbe** [comment] 2021-04-02 16:18
This issue appears to still occur when using docker container: [sha-c845a941](https://hub.docker.com/r/pdal/pdal/tags?page=1&ordering=last_updated&name=sha-c845a941) (or [2.2.](https://hub.docker.com/r/pdal/pdal/tags?page=1&ordering=last_updated&name=2.2))

{
    "pipeline": [{
        "type": "readers.ept",
        "filename": "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MI_BranchCo_2017_LAS_2019/ept.json",
        "bounds": "([-9483250.683171479, -9476065.602512673], [5124739.6706367135,5130376.9014727445])"
    },    {
        "type": "filters.range",
        "limits":"Classification[2:2]"
    },
    {
        "type":"filters.reprojection",
        "in_srs":"EPSG:3857",
        "out_srs":"EPSG:26916"
    },{
        "type" : "writers.las",
        "filename": "/data/points_viaDocker.laz",
        "a_srs": "EPSG:26916"
    }]}


docker run -v $PWD:/data pdal/pdal:sha-c845a941 pdal pipeline /data/pipeline_docker.json

**Comment by hobu** [comment] 2021-04-02 17:50
Confirmed this is not fixed with latest container.

**Closed** 2021-04-09 19:58 UTC
