### ISSUE TITLE
File globbing is not supported for JSON pipelines

### ISSUE THREAD

**Issue by baskinomics** [PDAL/PDAL#1347] opened 2016-11-01 03:49 UTC
The documentation on [Globbed Inputs](http://www.pdal.io/pipeline.html?highlight=glob#globbed-inputs) states 

`Finally, we capture another merge pipeline demonstrating the ability to glob multiple input LAS files from a given directory.`

and provides the following snippet:

```json
{
    "pipeline":[
        "/path/to/data/\*.las",
        {
            "type":"merge"
        },
        "output.las"
    ]
}
```

Aside from `"/path/to/data/\*.las"` not being valid JSON string, digging through the mailing list led me to this [thread](https://lists.osgeo.org/pipermail/pdal/2016-May/000983.html); with the statement

`This error is also correct and simply indicates that we're not supporting
globbing.  Should we provide a more specific error for this case for now?`

**Comment by connormanning** [comment] 2016-11-01 03:59
With current master, globbing should be available (aside from the bad backslash in the docs).  For example, [this pipeline](https://github.com/PDAL/PDAL/blob/master/test/data/pipeline/glob.json.in) is an active unit test for globbed inputs.

For more detail on the specifics of the globbing behavior, see [this recent PR](https://github.com/PDAL/PDAL/pull/1341).

**Comment by abellgithub** [comment] 2016-11-01 14:07
Duplicate of #1341 and #1345.  Now fixed.

**Closed by abellgithub** 2016-11-01 14:07 UTC
