### ISSUE TITLE
Compilation fails with GDAL 3.7.0rc1

### ISSUE THREAD

**Issue by nilason** [PDAL/PDAL#4036] opened 2023-05-02 17:32 UTC
**Describe the bug**
Compilation of PDAL (2.5.3) fails with recently released GDAL 3.7.0rc1. See log extract below:

<details>
  
```
/usr/bin/clang++ -DUNIX -Dpdalcpp_EXPORTS -I/opt/local/var/macports/build/_Users_me_ports_gis_pdal/PDAL/work/PDAL-2.5.3-src/vendor/gtest/include -I/opt/local/var/macports/build/_Users_me_ports_gis_pdal/PDAL/work/PDAL-2.5.3-src/vendor/gtest -I/opt/local/var/macports/build/_Users_me_ports_gis_pdal/PDAL/work/PDAL-2.5.3-src -I/opt/local/var/macports/build/_Users_me_ports_gis_pdal/PDAL/work/build/include -I/opt/local/var/macports/build/_Users_me_ports_gis_pdal/PDAL/work/PDAL-2.5.3-src/vendor -I/opt/local/var/macports/build/_Users_me_ports_gis_pdal/PDAL/work/PDAL-2.5.3-src/vendor/eigen -I/opt/local/var/macports/build/_Users_me_ports_gis_pdal/PDAL/work/PDAL-2.5.3-src/vendor/nlohmann -I/opt/local/var/macports/build/_Users_me_ports_gis_pdal/PDAL/work/PDAL-2.5.3-src/vendor/utfcpp/source -I/opt/local/include -I/opt/local/include/libxml2 -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -g -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -mmacosx-version-min=12.0 -fPIC -Wall -Wextra -Wpointer-arith -Wcast-align -Wcast-qual -Wno-error=parentheses -Wno-error=cast-qual -Wredundant-decls -Wno-unused-parameter -Wno-unused-variable -Wno-long-long -Wno-unknown-pragmas -Wno-deprecated-declarations -Wno-unknown-warning-option -fvisibility=hidden -fvisibility-inlines-hidden -std=c++17 -MD -MT CMakeFiles/pdalcpp.dir/pdal/Geometry.cpp.o -MF CMakeFiles/pdalcpp.dir/pdal/Geometry.cpp.o.d -o CMakeFiles/pdalcpp.dir/pdal/Geometry.cpp.o -c /opt/local/var/macports/build/_Users_me_ports_gis_pdal/PDAL/work/PDAL-2.5.3-src/pdal/Geometry.cpp

...

/opt/local/var/macports/build/_Users_me_ports_gis_pdal/PDAL/work/PDAL-2.5.3-src/pdal/Geometry.cpp:156:26: error: cannot initialize a variable of type 'OGRSpatialReference *' with an rvalue of type 'const OGRSpatialReference *'
    OGRSpatialReference *srs = m_geom->getSpatialReference();
                         ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_Users_me_ports_gis_pdal/PDAL/work/PDAL-2.5.3-src/pdal/Geometry.cpp:175:26: error: cannot initialize a variable of type 'OGRSpatialReference *' with an rvalue of type 'const OGRSpatialReference *'
    OGRSpatialReference *inSrs = m_geom->getSpatialReference();
                         ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/pdalcpp.dir/pdal/Geometry.cpp.o] Error 1
```

</details>

**Expected behavior**
Compilation should succeed.

**System/installation information:**
Please provide information on your PDAL version (`pdal --version`) and system (e.g., `uname -a` or `ver`).

```
macOS v12.6.3 arm64
```

**Comment by hobu** [comment] 2023-05-02 17:33
Duplicate of #4030

**Closed by hobu** 2023-05-02 17:33 UTC

**Comment by nilason** [comment] 2023-05-02 17:49
> Duplicate of #4030

Overlooked that one. Sorry for the noise.
