### ISSUE TITLE
Expression filter does not maintain faces in mesh

### ISSUE THREAD

**Issue by simplelife2010** [PDAL/PDAL#4494] opened 2024-09-06 13:21 UTC
Like in CloudCompare, I try to filter a mesh generated by the poisson filter by density like this:

```
[
    {
        "type" : "readers.ply",
        "filename": "poisson.ply"
    },
    {
        "type": "filters.expression",
        "expression": "(Density >= 14)"
    },
    {
        "type":"writers.ply",
        "faces":true,
        "filename":"trimmed.ply"
    }
]
```
The output file contains the filtered points, but the faces are gone
```
element face 0
```

**Expected behavior**
I would like to filter a mesh by an attribute like "density" and keep the faces.

**System/installation information:**

pdal version (git):
```
59fa11
```

**Comment by abellgithub** [comment] 2024-09-06 13:39
Duplicate of #3307

**Closed by abellgithub** 2024-09-06 13:39 UTC
